### ISSUE TITLE
Multiple Correct answers & non case-sensitive answers

### ISSUE THREAD

**Issue by Uber-blitz** [DennisOchulor/mc-flashcards#1]
I'm using this mod for language learning, the problem is that variation of wording and capitalisation can make or break the flashcard. having multiple answers that are not case sensitive would not only make studying easier, but makes the frustration of getting an answer wrong for a wrong word less of an issue.

**Comment by DennisOchulor** [comment]
Answers are already validated in a case insensitive way. As for variation in wording, having multiple correct answers would indeed help but I personally think doing it the way flashcard apps like Anki do it might be better. Let the _player themselves_ decide if they got the answer correct or wrong. In hindsight maybe I should have made the mod like that from the start but I could add that in as a configuration option in the future.

**Comment by DennisOchulor** [comment]
The option to manually validate answers has been added to v1.4.0, so this issue is considered resolved.
